#!/usr/bin/env python3
"""Top-40 by stability/universality (exploratory; Joseph's 2026-10-03 ask).

For every candidate (harness/top40/candidates.py) and every judge that ran the top40 battery:
  step score  = (adjacent steps that are consistent-directed — both presentation orders name the same
                 winner — in the judge's dominant direction along the surveyor's written order) / (all steps)
  gestalt     = mean direction-agnostic |Kendall tau| over 2 shuffles (⟂ counts as 0)
Per candidate:
  stability   = mean step score over judges
  universality= share of judges whose step score >= 0.8 (they confirm essentially every rung)
  floor       = lowest step score among frontier judges (the weakest frontier mind)
Ranking: stability, then gestalt, then universality. Small local models are reported but kept out of the
ranking pool by default (their position biases dominate; --all includes them).

  score.py [--all] [--out analysis/top40.md]
"""
import argparse, json, pathlib, sys
from collections import defaultdict
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "runner"))
import analyze_v1 as A

EXP = pathlib.Path(__file__).resolve().parents[2]
SMALL = {"llama32-3b", "qwen3-4b", "gemma3-4b", "phi4mini", "hermes3-3b", "mistral7b", "qwen25-3b"}

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--all", action="store_true")
    ap.add_argument("--out", default=str(EXP / "analysis/top40.md")); a = ap.parse_args()
    cands = {c["cand"]: c for c in json.load(open(EXP / "data/stimuli-v1/top40-candidates.json"))["candidates"]}
    stim = A.load_stimuli()
    for f in ("top40-steps.jsonl", "top40-gestalt.jsonl", "top40b-steps.jsonl", "top40b-gestalt.jsonl"):
        for line in open(EXP / "data/stimuli-v1" / f):
            r = json.loads(line); stim[r["pid"]] = r
    runs = A.load_runs(stim)
    steps = defaultdict(dict)   # judge -> cand -> score
    gest = defaultdict(dict)
    judges_seen = set()
    for r in runs:
        lab = r["spec"]["judge_label"]
        if r["spec"]["instrument"] in ("top40", "top40b"):
            judges_seen.add(lab)
            pres = defaultdict(dict)
            for (rep, pid), v in r["parsed"].items():
                s = stim[pid]; pres[(s["cand"], s["step"])][s["order"]] = (v, s)
            per = defaultdict(lambda: [0, 0, 0])  # up, down, n
            for (cand, k), d in pres.items():
                per[cand][2] += 1
                if 0 in d and 1 in d:
                    pv = A.pair_verdict(d[0][0], d[1][0])
                    if pv[0] == "dir":
                        per[cand][0 if pv[1] == d[0][1]["later"] else 1] += 1
            for cand, (up, down, n) in per.items():
                steps[lab][cand] = (max(up, down) / n, "up" if up >= down else "down", up, down, n)
        elif r["spec"]["instrument"] in ("top40-gestalt", "top40b-gestalt"):
            per = defaultdict(list)
            for (rep, pid), g in r["parsed"].items():
                s = stim[pid]; cand = int(s["seq"].split("-")[1])
                t = A.kendall_abs(g["order"], s["intended"]) if g.get("kind") == "order" else 0.0
                per[cand].append(t or 0.0)
            for cand, ts in per.items():
                gest[lab][cand] = sum(ts) / len(ts)
    pool = sorted(j for j in judges_seen if a.all or j not in SMALL)
    rows = []
    for cand, c in cands.items():
        sc = [steps[j][cand][0] for j in pool if cand in steps[j]]
        gs = [gest[j][cand] for j in pool if cand in gest[j]]
        if not sc:
            continue
        dirs = [steps[j][cand][1] for j in pool if cand in steps[j]]
        rows.append({"cand": cand, "glyphs": "".join(c["glyphs"]), "n_surveyors": c["n_surveyors"],
                     "stability": sum(sc) / len(sc), "floor": min(sc), "universality": sum(x >= 0.8 for x in sc) / len(sc),
                     "gestalt": (sum(gs) / len(gs)) if gs else None, "n_judges": len(sc),
                     "direction_split": f"{dirs.count('up')}↑/{dirs.count('down')}↓",
                     "per_judge": {j: round(steps[j][cand][0], 2) for j in pool if cand in steps[j]},
                     "small_models": {j: round(steps[j][cand][0], 2) for j in sorted(judges_seen & SMALL) if cand in steps[j]}})
    rows.sort(key=lambda r: (-r["stability"], -(r["gestalt"] or 0), -r["universality"], r["cand"]))
    out = ["# Top-40 glyph sequences by stability and universality (exploratory) — generated by harness/top40/score.py\n",
           f"Judges in the ranking pool: {', '.join(pool)}. Small local models ({', '.join(sorted(judges_seen & SMALL)) or 'none yet'}) are shown in the last column but do not enter the ranking.\n",
           "Candidates: 117 survey sequences chosen by cross-surveyor concordance (harness/top40/candidates.py): batch a (0–63) was selected while a bug hid the grok-1 and sonnet-survey-3/4 records; batch b (64–116) adds every record with support from ≥ 2 of the 7 surveys not already covered. Surveyor counts are recomputed over all 7. Every adjacent rung was tested in both presentation orders with ⟂ and ≈ available; each whole set was reconstructed from 2 shuffles.\n",
           "*Stability* = mean over judges of the share of rungs confirmed (both orders agree, running the same way along the surveyor's order). *Universality* = share of judges confirming ≥ 80% of rungs. *Floor* = the weakest judge's rung share. *Gestalt* = mean |τ| of whole-set reconstruction. Direction = how many judges read the written order as ascending (↑) vs descending (↓).\n",
           "| # | sequence | stability | universality | floor | gestalt | surveyors | direction | small local models |",
           "|---|---|---|---|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        g = f"{r['gestalt']:.2f}" if r["gestalt"] is not None else "–"
        sm = " ".join(f"{k}:{v:.2f}" for k, v in r["small_models"].items()) or "–"
        out.append(f"| {i} | `{r['glyphs']}` | {r['stability']:.2f} | {r['universality']:.2f} | {r['floor']:.2f} | {g} | {r['n_surveyors']}/7 | {r['direction_split']} | {sm} |")
        if i == 40:
            out.append("| | *— below the top 40 —* | | | | | | | |")
    open(a.out, "w").write("\n".join(out) + "\n")
    json.dump(rows, open(pathlib.Path(a.out).with_suffix(".json"), "w"), ensure_ascii=False, indent=1)
    print("\n".join(out[:50]))

if __name__ == "__main__":
    main()
