#!/usr/bin/env python3
"""Progress per round: is the loop growing more stable sequences, and at what cost?

  progress.py [--data DIR]        -> DIR/PROGRESS.md, DIR/progress.json (and printed); for the study also <study>/PROGRESS.md

For each round, from every answer up to and including it, the sequences growth.py grows (the same rows as STANDINGS.md):
  calls        sheets answered that round, across minds (cost); cum calls: cumulative
  sequences    all grown rows; longest; glyphs in them
  stable       rows whose every step was given by minds of >= 2 families (growth.stable; a read-off, it gates nothing),
               by length; stable glyphs = glyphs in stable rows
  cycles       rows that close on themselves
  untested     steps of rows no answer has given yet (insertion creates them; the planner asks them next)
Synthetic runs: also planted sequences recovered (a row with exactly the planted glyphs in the planted order).
"""
import argparse, collections, json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from common import EXP, read_jsonl
import model as M
import round as RD
import growth as G

def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--data"); a = ap.parse_args()
    d = pathlib.Path(a.data) if a.data else EXP / "data"
    synth = json.load(open(d / "pool.json")).get("synth")
    fam = RD.family_of(d)
    rows = []
    for rid in RD.rounds(d):
        rdir = d / "rounds" / rid
        calls = sum(1 for f in rdir.glob("raw/*/ledger.jsonl") for row in read_jsonl(f)
                    if row["result"].get("raw") and not row["result"].get("error"))
        if not calls:
            continue
        items, pres, parsed, sheets = RD.load_all(d, upto=rid)
        seqs, fams, live = G.build(M.observations(parsed, pres), parsed, pres, fam)
        st = [s for s in seqs if G.stable(s)]
        bk = collections.Counter(G.bucket(len(s["glyphs"])) for s in st)
        sl = sorted(len(s["glyphs"]) for s in st)
        scheme = json.load(open(rdir / "plan.json")).get("scheme", "disagreement-ranked") if (rdir / "plan.json").exists() else "probe"
        row = {"round": rid, "scheme": scheme.split(" ")[0], "calls": calls, "sequences": len(seqs),
               "longest": max((len(s["glyphs"]) for s in seqs), default=0), "glyphs": sum(len(s["glyphs"]) for s in seqs),
               "stable": len(st), "stable_glyphs": sum(sl), "stable_longest": sl[-1] if sl else 0,
               "cycles": sum(s["cyclic"] for s in seqs),
               "untested": sum(1 for s in seqs for x in s["steps"] if x["answers"] == 0),
               **{"b" + k: bk[k] for k in ("3", "4–5", "6–7", "8–9", "10+")}}
        if synth:
            import synth as S
            w = S.world_default()
            ok = 0
            for steps in w["seqs"].values():
                tg = [g for stp in steps for g in stp]
                ok += any(s["glyphs"] in (tg, tg[::-1]) for s in seqs)
            row["planted_recovered"] = f"{ok}/{len(w['seqs'])}"
        rows.append(row)
    L = ["# Progress by round", "",
         f"*Generated by `harness/seq/progress.py` from every answer in `{d}`, round by round, with the same growth as `STANDINGS.md` (`growth.py`; nothing filtered). "
         "**Stable:** every step of the row was given by minds of two or more LLM families; a read-off, it filters nothing. "
         "**Untested:** steps of rows no answer has given yet; the planner asks them next. "
         "**Calls:** sheets answered that round, across minds. The line to watch is stable glyphs against cumulative calls: is each round still adding stable structure?*", "",
         "| round | scheme | calls | cum calls | sequences | longest | stable | stable glyphs | longest stable | len 3 | 4–5 | 6–7 | 8–9 | 10+ | cycles | untested |"
         + (" planted recovered |" if synth else ""),
         "|" + "---|" * (16 + bool(synth))]
    cum = 0
    for r in rows:
        cum += r["calls"]
        L.append(f"| {r['round']} | {r['scheme']} | {r['calls']} | {cum} | {r['sequences']} | {r['longest']} | {r['stable']} | {r['stable_glyphs']} | {r['stable_longest']} | "
                 f"{r['b3']} | {r['b4–5']} | {r['b6–7']} | {r['b8–9']} | {r['b10+']} | {r['cycles']} | {r['untested']} |"
                 + (f" {r['planted_recovered']} |" if synth else ""))
    json.dump(rows, open(d / "progress.json", "w"), indent=0, ensure_ascii=False)
    out = "\n".join(L) + "\n"
    (d / "PROGRESS.md").write_text(out)
    if d == EXP / "data":
        (EXP / "PROGRESS.md").write_text(out)
    print(out)

if __name__ == "__main__":
    main()
