#!/usr/bin/env python3
"""A read-off, not a concern: the best-confirmed stretches of sequence in the tree right now. It reads the tree and
writes BEST.md; nothing reads BEST.md back (the planner never sees it), so its definition of "best" cannot steer
probing, the tree, priority or the port.

"Best" here = CONFIRMED BY REAL MINDS, LONG, AND AGREED:
  - Candidates are the walks of the full tree (seed votes included, so seeded sequences are found quickly).
  - Each link between neighbouring glyphs of a walk is then checked on the PURE tree (real answers only, no seed
    votes): the link a->b is CONFIRMED when, reading left to right, the longest context ending at a that a real mind
    was shown has b as its most-agreed continuation -- or, reading right to left, the longest context ending at b has
    a -- with agreement >= THETA and given by minds of >= 2 families.
  - A stretch is a maximal run of confirmed links; it is listed when it has >= 3 glyphs. Stretches contained in a
    longer one (either direction) are that one.
  - Ranked by length, then by mean agreement over its links.
  - Manifested cycles (a mind wrote the whole period twice; >= 4 distinct glyphs) are listed first, apart.
THETA = 0.75 is a read-off cut chosen without evidence; it gates nothing anywhere else.
"""
import collections, pathlib, sys

HERE = pathlib.Path(__file__).resolve()
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "tree"))
import tree as TR                                           # noqa: E402

THETA = 0.75
TOP = 150

def support(Tp, left_run, x):
    """confirmation of x after left_run on the pure tree -> (agreement, families) or None"""
    for j in range(min(TR.MAXK, len(left_run)), 1, -1):
        ctx = tuple(left_run[-j:])
        if ctx in Tp.nodes:
            rk = Tp.ranked(ctx)
            if rk and rk[0][0] == x:
                agr, nfam, _ = rk[0][1]
                if agr >= THETA and nfam >= 2:
                    return agr, nfam
            return None                                     # the longest asked context decides
    return None

def stretches(g, Tp):
    n = len(g)
    links = []
    for i in range(n - 1):
        best = None
        if i + 1 >= 2:
            best = support(Tp, g[:i + 1], g[i + 1])          # left to right: g[i+1] after ...g[i]
        if i + 2 <= n - 1:
            b = support(Tp, g[i + 1:][::-1], g[i])          # right to left: g[i] after ...g[i+1] (reversed)
            if b and (best is None or b[0] > best[0]):
                best = b
        links.append(best)
    out, cur = [], []
    for i, lk in enumerate(links + [None]):
        if lk:
            cur.append((i, lk))
        else:
            if len(cur) >= 2:
                a, b = cur[0][0], cur[-1][0] + 1
                out.append({"glyphs": g[a:b + 1], "agreement": sum(l[1][0] for l in cur) / len(cur),
                            "families_min": min(l[1][1] for l in cur)})
            cur = []
    return out

def main():
    recs = TR.load()
    T = TR.Tree(recs, seeds=True)
    Tp = TR.Tree(recs, seeds=False)
    found = {}
    for s in TR.sequences(T):
        for st in stretches(s["glyphs"], Tp):
            key = tuple(min(st["glyphs"], st["glyphs"][::-1]))
            if key not in found or st["agreement"] > found[key]["agreement"]:
                found[key] = st
    items = sorted(found.values(), key=lambda s: -len(s["glyphs"]))
    kept = []
    for s in items:
        g, n = s["glyphs"], len(s["glyphs"])
        if not any(n < len(k["glyphs"]) and any(k["glyphs"][i:i + n] in (g, g[::-1]) for i in range(len(k["glyphs"]) - n + 1)) for k in kept):
            kept.append(s)
    kept.sort(key=lambda s: (-len(s["glyphs"]), -s["agreement"], s["glyphs"]))
    cyc = sorted((c for c in Tp.cycles.values() if c["distinct"] >= 4), key=lambda c: (-len(c["families"]), -c["answers"]))
    rounds = sorted({r["round"] for r in recs if r["round"] != "seed"}, key=lambda x: (x[0] != "r", x))
    lens = collections.Counter(min(len(s["glyphs"]), 10) for s in kept)
    L = ["# Best-confirmed sequences", "",
         f"*Generated by `refactored/report/best.py` after {rounds[-1]}. This is a read-off: nothing reads it back, so it never steers what is asked. A **stretch** is a run of glyphs in which every link between neighbours was confirmed by real minds, reading in either direction: the longest context the minds were shown names the next glyph as its most-agreed continuation, with agreement ≥ {THETA} and from ≥ 2 LLM families. Seed votes help find candidates but never confirm a link. Stretches are ranked by length, then by mean agreement. The full tree, with branches and open ends, is in `SEQUENCES.md`.*", "",
         f"**{len(kept)} confirmed stretches of 3+ glyphs** (by length: " + ", ".join(f"{k if k < 10 else '10+'}: {lens[k]}" for k in sorted(lens)) + f"); **{len(cyc)} manifested cycles.**", ""]
    if cyc:
        L += ["## Cycles (manifested: a mind wrote the whole period twice)", "", "| cycle | glyphs | answers | families |", "|---|---|---|---|"]
        L += [f"| `{' '.join(c['pattern'])} ↻` | {len(c['pattern'])} | {c['answers']} | {', '.join(sorted(c['families']))} |" for c in cyc[:40]]
        L.append("")
    L += ["## Stretches", "", "| # | stretch | glyphs | mean agreement | families (min over links) |", "|---|---|---|---|---|"]
    for i, s in enumerate(kept[:TOP], 1):
        L.append(f"| {i} | `{' '.join(s['glyphs'])}` | {len(s['glyphs'])} | {s['agreement']:.2f} | {s['families_min']} |")
    if len(kept) > TOP:
        L += ["", f"*{len(kept) - TOP} shorter stretches not shown.*"]
    (ROOT / "BEST.md").write_text("\n".join(L) + "\n")
    print("\n".join(L[:12]))

if __name__ == "__main__":
    main()
