#!/usr/bin/env python3
"""Write data/runs-v1/INVENTORY.md: one row per run dir (calls, successful calls, failed/incomplete,
time span, provider-reported model ids, list-price cost where reported, sha256 of the ledger file).
Derived and regenerable; the ledgers are the record."""
import collections, hashlib, json, pathlib
EXP = pathlib.Path(__file__).resolve().parents[2]
R = EXP / "data/runs-v1"
rows = []
for d in sorted(p for p in R.iterdir() if p.is_dir()):
    led = d / "ledger.jsonl"
    if not led.exists():
        continue
    n = ok = bad = 0; ts = []; models = collections.Counter(); cost = 0.0
    for line in open(led):
        r = json.loads(line); n += 1; res = r["result"]
        if res.get("raw") and not res.get("error") and r.get("sheet_incomplete") is None:
            ok += 1
        else:
            bad += 1
        if r.get("ts"): ts.append(r["ts"])
        if res.get("model_reported"): models[res["model_reported"]] += 1
        cost += res.get("cost_usd") or 0
    sha = hashlib.sha256(led.read_bytes()).hexdigest()[:16]
    rows.append(f"| {d.name} | {n} | {ok} | {bad} | {min(ts)[:16] if ts else ''} → {max(ts)[11:16] if ts else ''} | "
                f"{', '.join(m for m, _ in models.most_common(2))} | {cost:.2f} | `{sha}` |")
out = ["# runs-v1 inventory (generated by harness/runner/inventory.py — do not hand-edit)\n",
       "Rows whose names end in `-shakedown` or contain `-aborted` are excluded from every analysis. 'ok' = calls with a raw answer, no adapter error, and (sheet mode) ≥ 90% of items parseable at write time. Failed or incomplete calls stay in the ledger verbatim; resumed runs re-ask them.\n",
       "| run | calls | ok | failed / incomplete | UTC span | model reported | list cost USD | ledger sha256[:16] |",
       "|---|---|---|---|---|---|---|---|"] + rows
(R / "INVENTORY.md").write_text("\n".join(out) + "\n")
print(len(rows), "runs")
